name: gymsnap
description: "Gym Equipment Classification."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  bottom_sheet: ^4.0.4
  http: ^1.3.0
  get_it: ^8.0.3
  camerawesome: ^2.1.0
  image: ^4.5.3
  image_picker: ^1.1.2
  http_parser: ^4.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: 'assets/images/gymsnap.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/