"""Update database.

Revision ID: 267c8d898861
Revises: a9cff48111f8
Create Date: 2025-03-25 00:36:51.508867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267c8d898861'
down_revision = 'a9cff48111f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('exercises')
    op.drop_table('secondary_muscle_association')
    op.drop_table('muscles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscles',
    sa.Column('id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_muscle_association',
    sa.Column('exercise_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('muscle_id', sa.VARCHAR(length=120), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('equipment_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('secondary_equipment_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('muscle_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('level', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.ForeignKeyConstraint(['secondary_equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
