"""Initial migration

Revision ID: 3318b4ed9d9e
Revises: 
Create Date: 2025-03-05 11:19:46.522374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3318b4ed9d9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('secondary_equipment_id', sa.Integer(), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.ForeignKeyConstraint(['secondary_equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_muscle_association',
    sa.Column('exercise_id', sa.String(length=120), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_muscle_association')
    op.drop_table('exercises')
    op.drop_table('muscles')
    op.drop_table('equipment')
    # ### end Alembic commands ###
